// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgnjhblwjjkxpdaqsfbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnbmpoYmx3ampreHBkYXFzZmJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzY3MTMsImV4cCI6MjA2NjQ1MjcxM30.sHX2xrgKVy_YXdsrN1F7joBH0pDYydMeEJmX92c68Do";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);